import React, { createContext, useContext, useState, useEffect } from "react";

interface LanguageContextType {
  language: "en" | "ar";
  setLanguage: (lang: "en" | "ar") => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
       "pageTitle": "Orders Management",
      "searchPlaceholder": "Search",
      "filterAll": "All Statuses",
      "filterPending": "Pending",
      "filterProcessing": "Processing",
      "filterConfirmed": "Confirmed",
      "filterShipped": "Shipped",
      "filterDelivered": "Delivered",
      "filterCancelled": "Cancelled",
      "refreshBtn": "Refresh",
      "loading": "Loading...",
      "orderNumber": "Order Number",
      "customer": "Customer",
      "total": "Total",
      "status": "Status",
      "createdAt": "Created At",
      "actions": "Actions",
      "view": "View",
      "edit": "Edit",
      "manageStatus": "Manage Order Status",
      "changeStatus": "Change Status",
      "updateStatusBtn": "Update Status",
      "cancelOrderBtn": "Cancel Order",
      "orderDetails": "Order Details",
      "shippingAddress": "Shipping Address",
      "paymentMethod": "Payment Method",
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.services": "Services",
    "nav.dashboard": "Dashboard",
    "nav.admin": "Admin",
    "nav.affiliate": "Affiliate",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "nav.register": "Register",

    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.price": "Price",
    "common.points": "Points",
    "common.total": "Total",
    "common.chooseFile": "Choose File",
    "common.noFileChosen": "No file chosen",
    "common.sending": "Sending...",

    // Home
    "home.hero.title": "Your Premier Network Solutions Hub",
    "home.hero.subtitle":
      "Discover cutting-edge network devices, software licenses, and professional installation services",
    "home.hero.cta": "Explore Products",
    "home.features.title": "Why Choose StoreHub?",
    "home.features.devices": "Premium Network Devices",
    "home.features.devices.desc": "Latest networking equipment from top brands",
    "home.features.licenses": "Software Licenses",
    "home.features.licenses.desc":
      "Genuine software licenses with instant delivery",
    "home.features.installation": "Installation Services",
    "home.features.installation.desc": "Professional setup and configuration",

    // Products
    "products.title": "Our Products",
    "products.category.all": "All Products",
    "products.category.network-device": "Network Devices",
    "products.category.software-license": "Software Licenses",
    "products.category.installation-service": "Installation Services",
    "products.addToCart": "Add to Cart",
    "products.outOfStock": "Out of Stock",
    "products.allBrands": "All Brands",
    "products.search": "Search products...",
    "products.sortByName": "Sort by Name",
    "products.sortByPrice": "Sort by Price",
    "products.sortByCategory": "Sort by Category",

    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty.title": "Your cart is empty",
    "cart.empty.subtitle": "Add some products to get started",
    "cart.empty.cta": "Browse Products",
    "cart.itemsCount": "items in cart",
    "cart.items": "Cart Items",
    "cart.summary": "Order Summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.freeShipping": "Free",
    "cart.promoCode": "Promo Code",
    "cart.promoCode.placeholder": "Enter code",
    "cart.usePoints": "Use points for discount",
    "cart.discount": "discount",
    "cart.pointsDiscount": "Points Discount",
    "cart.checkout": "Proceed to Checkout",
    "cart.clear": "Clear Cart",
    "common.apply": "Apply",

    // Checkout
    "checkout.title": "Checkout",
    "checkout.subtitle": "Fill shipping information and choose payment method.",
    "checkout.shipping": "Shipping Information",
    "checkout.name": "Full name",
    "checkout.email": "Email",
    "checkout.phone": "Phone",
    "checkout.address1": "Address line 1",
    "checkout.address2": "Address line 2 (optional)",
    "checkout.city": "City",
    "checkout.state": "State",
    "checkout.country": "Country",
    "checkout.postalCode": "Postal Code *",
    "checkout.notes": "Order notes (optional)",
    "checkout.payment": "Payment Method",
    "checkout.cod": "Cash on Delivery (Full)",
    "checkout.codDesc": "Pay full amount on delivery.",
    "checkout.split": "Split Payment (Deposit + Final)",
    "checkout.splitDesc": "Pay deposit now, remaining amount upon service completion",
    "checkout.summary": "Order Summary",
    "checkout.processing": "Processing...",
    "checkout.placeOrder": "Place order",
    "checkout.fillRequired": "Please fill all required shipping fields",
    "checkout.success": "Order created successfully",
    "checkout.failed": "Failed to create order",
    "common.back": "Back",

    // Services
    "services.title": "Network Services",
    "services.subtitle": "Professional network installation, configuration, and maintenance services by certified experts.",
    "services.search": "Search services...",
    "services.sortByName": "Sort by Name",
    "services.sortByPrice": "Sort by Price",
    "services.requestService": "Request Service",
    "services.features": "Features",
    "services.moreFeatures": "more features",
    "services.deposit": "Deposit",
    "services.loading": "Loading services...",
    "services.noServices": "No services found matching your criteria.",
    "services.allDurations": "All Durations",
    "services.duration.1-2_hours": "1-2 Hours",
    "services.duration.half_day": "Half Day (4 hours)",
    "services.duration.full_day": "Full Day (8 hours)",
    "services.duration.2-3_days": "2-3 Days",
    "services.duration.1_week": "1 Week",
    "services.duration.2_weeks": "2 Weeks",
    "services.duration.1_month": "1 Month",
    "services.duration.custom": "Custom Duration",

    // Orders
    "orders.title": "Order Details",
    "orders.notFound": "Order not found",
    "orders.backToDashboard": "← Back to Dashboard",
    "orders.cancel": "Cancel Order",
    "orders.cancelConfirm": "Are you sure you want to cancel this order?",
    "orders.cancelled": "Order cancelled successfully",
    "orders.cancelFailed": "Failed to cancel order",
    "orders.orderNumber": "Order Number",
    "orders.date": "Date",
    "orders.total": "Total",
    "orders.status": "Status",
    "orders.paymentStatus": "Payment Status",
    "orders.shippingInfo": "Shipping Information",
    "orders.items": "Order Items",
    "orders.product": "Product",
    "orders.service": "Service",

    // Home
    "home.stats.customers": "Happy Customers",
    "home.stats.products": "Products Available",
    "home.stats.countries": "Countries Served",
    "home.stats.experience": "Years Experience",
    "home.features.subtitle": "Premium networking solutions designed for stability & performance",
    "home.cta.title": "Ready to transform your infrastructure?",
    "home.cta.subtitle": "Join thousands of professionals using StoreHub to power their networks.",
    "home.cta.browse": "Browse Products",
    "home.cta.createAccount": "Create Account",

    // Profile
    "profile.title": "Profile Settings",
    "profile.subtitle": "Manage your account settings and preferences",
    "profile.tabs.profile": "Profile",
    "profile.tabs.security": "Security",
    "profile.tabs.notifications": "Notifications",
    "profile.tabs.preferences": "Preferences",
    "profile.phone": "Phone Number",
    "profile.address": "Address",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmPassword": "Confirm Password",
    "profile.changePassword": "Change Password",
    "profile.notifications.email": "Email Notifications",
    "profile.notifications.email.desc": "Receive notifications via email",
    "profile.notifications.push": "Push Notifications",
    "profile.notifications.push.desc": "Receive push notifications",
    "profile.notifications.sms": "SMS Notifications",
    "profile.notifications.sms.desc": "Receive notifications via SMS",
    "profile.language": "Language",
    "profile.language.desc": "Choose your preferred language",
    "profile.theme": "Theme",
    "profile.theme.desc": "Choose your preferred theme",
    "profile.theme.light": "Light Mode",
    "profile.theme.dark": "Dark Mode",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.unread": "unread notifications",
    "notifications.allRead": "All notifications read",
    "notifications.markAllRead": "Mark all as read",
    "notifications.clearAll": "Clear all",
    "notifications.filter.all": "All",
    "notifications.filter.unread": "Unread",
    "notifications.filter.read": "Read",
    "notifications.empty.title": "No notifications",
    "notifications.empty.subtitle": "You're all caught up!",
    "notifications.markRead": "Mark as read",
    "notifications.delete": "Delete",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.stats.orders": "Total Orders",
    "dashboard.stats.points": "Points Balance",
    "dashboard.stats.spent": "Total Spent",
    "dashboard.recentOrders": "Recent Orders",
    "dashboard.pointsHistory": "Points History",
    "dashboard.myOrders": "My Orders",
    "dashboard.noOrders": "No orders yet",
    "dashboard.startShopping": "Start shopping to see your orders here.",
    "dashboard.order": "Order",
    "dashboard.items": "items",
    "dashboard.status": "Status",
    "dashboard.paymentPending": "Payment Pending",
    "dashboard.estimatedDelivery": "Estimated delivery",
    "dashboard.processingOrders": "Processing Orders",

    // Admin
    "admin.title": "Admin Dashboard",
    "admin.users": "Users",
    "admin.products": "Products",
    "admin.orders": "Orders",
    "admin.analytics": "Analytics",
    "admin.notifications": "Notifications",

    // Auth
    "auth.login.title": "Sign In",
    "auth.login.subtitle": "Welcome back to StoreHub",
    "auth.register.title": "Create Account",
    "auth.register.subtitle": "Join StoreHub today",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.phone": "Phone Number",
    "auth.name": "Full Name",
    "auth.role": "Account Type",
    "auth.role.individual": "Individual",
    "auth.role.company_admin": "Company",
    "auth.role.company_staff": "Company Staff",
    "auth.role.affiliate": "Sales By Commission",
    "auth.companyName": "Company Name",

    "auth.register.companyName": "Company Name",
    "auth.register.companyName.placeholder": "Enter company name",
    "auth.register.companyEmail": "Company Email",
    "auth.register.companyEmail.placeholder": "Enter company email",
    "auth.register.companyEmail.hint":
      " You must use your official company email",
    "auth.register.commercialRegister": "Commercial Registration Image",
    "auth.register.taxCard": "Tax Card Image",
    "auth.register.affiliateCompany": "Company Name",
    "auth.register.affiliateCompany.placeholder": "Enter your company name",
    "auth.register.affiliateJobTitle": "Job Title",
    "auth.register.affiliateJobTitle.placeholder": "Enter your job title",
    "auth.register.affiliateReason": "Why do you want to work with us?",
    "auth.register.affiliateReason.placeholder": "Write your reason...",
    "auth.role.salesCommission": "Sales by Commission",
    "auth.register.name.placeholder": "Enter your full name",
    "auth.register.email.placeholder": "Enter your email",
    "auth.register.password.placeholder": "Create a password",
    "auth.register.haveAccount": "Already have an account?",

    "auth.register.phoneRequired": "Phone number is required",
    "auth.register.phoneInvalid": "Invalid  phone number",
    "auth.register.phone.placeholder": "Enter your phone number",

    "auth.forgotPassword.title": "Forgot Your Password ?",
    "auth.forgotPassword.subtitle":
      "Enter your email address below and we'll send you code to reset your password.",
    "auth.forgotPassword.emailPlaceholder": "Enter your email address",
    "auth.forgotPassword.sendCode": "Send Resent Code",
    "auth.forgotPassword.login": "Back to Login",
    "auth.forgotPassword.checkEmail": "Check your email",
    "auth.forgotPassword.sentTo": "We have sent a password reset code to",
    "auth.forgotPassword.enterCode": "Enter Reset Code",
    "auth.forgotPassword.codeSent": "Code has been sent ",

    "auth.resetPassword.title": "Reset Password",
    "auth.resetPassword.subtitle": "Enter the reset code",
    "auth.resetPassword.newPassword": "New Password",
    "auth.resetPassword.newPasswordPlaceholder": "Enter your new password",
    "auth.resetPassword.confirmPassword": "Confirm New Password",
    "auth.resetPassword.confirmPasswordPlaceholder":
      "Confirm your new password",
    "auth.resetPassword.resetButton": "Reset Password",
    "auth.resetPassword.resetting": "Resetting Password...",
    "auth.resetPassword.resendCode": "Resend Code",
    "auth.resetPassword.didntReceive": "Didn't receive the code?",
    "auth.resetPassword.backToLogin": "Back to Login",

    // Login
    "auth.login.email": "Email",
    "auth.login.password": "Password",
    "auth.login.emailPlaceholder": "Enter your email",
    "auth.login.passwordPlaceholder": "Enter your password",
    "auth.login.forgotPassword": "Forgot Password?",
    "auth.login.dontHaveAccount": "Don't have an account?",
    "auth.login.noAccount": "Don't have an account?",
  },
  ar: {
      "pageTitle": "إدارة الطلبات",
      "searchPlaceholder": "بحث",
      "filterAll": "الكل",
      "filterPending": "قيد المراجعة",
      "filterProcessing": "قيد المعالجة",
      "filterConfirmed": "تم التأكيد",
      "filterShipped": "تم الشحن",
      "filterDelivered": "تم التوصيل",
      "filterCancelled": "ملغي",
      "refreshBtn": "تحديث",
      "loading": "جارٍ التحميل...",
      "orderNumber": "رقم الطلب",
      "customer": "العميل",
      "total": "الإجمالي",
      "status": "الحالة",
      "createdAt": "تاريخ الإنشاء",
      "actions": "إجراءات",
      "view": "عرض",
      "edit": "تعديل",
      "manageStatus": "إدارة حالة الطلب",
      "changeStatus": "تغيير حالة الطلب",
      "updateStatusBtn": "تحديث الحالة",
      "cancelOrderBtn": "إلغاء الطلب",
      "orderDetails": "تفاصيل الطلب",
      "shippingAddress": "العنوان",
      "paymentMethod": "طريقة الدفع",
    // Navigation
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.services": "الخدمات",
    "nav.dashboard": "لوحة التحكم",
    "nav.admin": "المدير",
    "nav.affiliate": "المسوق",
    "nav.company": "الشركة",
    "nav.profile": "الملف الشخصي",
    "nav.logout": "تسجيل خروج",
    "nav.login": "تسجيل دخول",
    "nav.register": "إنشاء حساب",

    // Common
    "common.loading": "جارٍ التحميل...",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.price": "السعر",
    "common.points": "النقاط",
    "common.total": "المجموع",
    "common.chooseFile": "اختر ملف",
    "common.noFileChosen": "لم يتم اختيار ملف",
    "common.sending": "جاري الإرسال...",

    // Home
    "home.hero.title": "مركز حلول الشبكات الرائد",
    "home.hero.subtitle":
      "اكتشف أحدث أجهزة الشبكات وتراخيص البرمجيات وخدمات التثبيت المهنية",
    "home.hero.cta": "استكشف المنتجات",
    "home.features.title": "لماذا تختار ستور هاب؟",
    "home.features.devices": "أجهزة شبكات متميزة",
    "home.features.devices.desc":
      "أحدث معدات الشبكات من أفضل العلامات التجارية",
    "home.features.licenses": "تراخيص البرمجيات",
    "home.features.licenses.desc": "تراخيص برمجيات أصلية مع التسليم الفوري",
    "home.features.installation": "خدمات التثبيت",
    "home.features.installation.desc": "إعداد وتكوين احترافي",

    // Products
    "products.title": "منتجاتنا",
    "products.category.all": "جميع المنتجات",
    "products.category.network-device": "أجهزة الشبكات",
    "products.category.software-license": "تراخيص البرمجيات",
    "products.category.installation-service": "خدمات التثبيت",
    "products.addToCart": "أضف للسلة",
    "products.outOfStock": "غير متوفر",
    "products.allBrands": "جميع العلامات",
    "products.search": "بحث عن المنتجات...",
    "products.sortByName": "ترتيب حسب الاسم",
    "products.sortByPrice": "ترتيب حسب السعر",
    "products.sortByCategory": "ترتيب حسب الفئة",

    // Cart
    "cart.title": "سلة التسوق",
    "cart.empty.title": "سلة التسوق فارغة",
    "cart.empty.subtitle": "أضف بعض المنتجات للبدء",
    "cart.empty.cta": "تصفح المنتجات",
    "cart.itemsCount": "عنصر في السلة",
    "cart.items": "عناصر السلة",
    "cart.summary": "ملخص الطلب",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن",
    "cart.freeShipping": "مجاني",
    "cart.promoCode": "كود الخصم",
    "cart.promoCode.placeholder": "أدخل الكود",
    "cart.usePoints": "استخدم النقاط للحصول على خصم",
    "cart.discount": "خصم",
    "cart.pointsDiscount": "خصم النقاط",
    "cart.checkout": "متابعة الدفع",
    "cart.clear": "إفراغ السلة",
    "common.apply": "تطبيق",

    // Checkout
    "checkout.title": "الدفع",
    "checkout.subtitle": "املأ معلومات الشحن واختر طريقة الدفع.",
    "checkout.shipping": "معلومات الشحن",
    "checkout.name": "الاسم الكامل",
    "checkout.email": "البريد الإلكتروني",
    "checkout.phone": "رقم الهاتف",
    "checkout.address1": "عنوان السطر الأول",
    "checkout.address2": "عنوان السطر الثاني (اختياري)",
    "checkout.city": "المدينة",
    "checkout.state": "المحافظة",
    "checkout.country": "الدولة",
    "checkout.postalCode": "الرمز البريدي *",
    "checkout.notes": "ملاحظات الطلب (اختياري)",
    "checkout.payment": "طريقة الدفع",
    "checkout.cod": "الدفع عند الاستلام (كامل)",
    "checkout.codDesc": "ادفع المبلغ الكامل عند الاستلام.",
    "checkout.split": "الدفع المقسم (عربون + نهائي)",
    "checkout.splitDesc": "ادفع العربون الآن، والمبلغ المتبقي عند اكتمال الخدمة",
    "checkout.summary": "ملخص الطلب",
    "checkout.processing": "جاري المعالجة...",
    "checkout.placeOrder": "تأكيد الطلب",
    "checkout.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "checkout.success": "تم إنشاء الطلب بنجاح",
    "checkout.failed": "فشل إنشاء الطلب",
    "common.back": "رجوع",

    // Services
    "services.title": "خدمات الشبكات",
    "services.subtitle": "خدمات تركيب وتكوين وصيانة الشبكات الاحترافية من قبل خبراء معتمدين.",
    "services.search": "بحث عن الخدمات...",
    "services.sortByName": "ترتيب حسب الاسم",
    "services.sortByPrice": "ترتيب حسب السعر",
    "services.requestService": "طلب الخدمة",
    "services.features": "المميزات",
    "services.moreFeatures": "مميزات إضافية",
    "services.deposit": "عربون",
    "services.loading": "جاري تحميل الخدمات...",
    "services.noServices": "لم يتم العثور على خدمات تطابق معايير البحث.",
    "services.allDurations": "جميع المدد",
    "services.duration.1-2_hours": "1-2 ساعة",
    "services.duration.half_day": "نصف يوم (4 ساعات)",
    "services.duration.full_day": "يوم كامل (8 ساعات)",
    "services.duration.2-3_days": "2-3 أيام",
    "services.duration.1_week": "أسبوع واحد",
    "services.duration.2_weeks": "أسبوعان",
    "services.duration.1_month": "شهر واحد",
    "services.duration.custom": "مدة مخصصة",

    // Orders
    "orders.title": "تفاصيل الطلب",
    "orders.notFound": "الطلب غير موجود",
    "orders.backToDashboard": "← العودة إلى لوحة التحكم",
    "orders.cancel": "إلغاء الطلب",
    "orders.cancelConfirm": "هل أنت متأكد من إلغاء هذا الطلب؟",
    "orders.cancelled": "تم إلغاء الطلب بنجاح",
    "orders.cancelFailed": "فشل إلغاء الطلب",
    "orders.orderNumber": "رقم الطلب",
    "orders.date": "التاريخ",
    "orders.total": "المجموع",
    "orders.status": "الحالة",
    "orders.paymentStatus": "حالة الدفع",
    "orders.shippingInfo": "معلومات الشحن",
    "orders.items": "عناصر الطلب",
    "orders.product": "منتج",
    "orders.service": "خدمة",

    // Home
    "home.stats.customers": "عملاء سعداء",
    "home.stats.products": "منتج متاح",
    "home.stats.countries": "دولة",
    "home.stats.experience": "سنة خبرة",
    "home.features.subtitle": "حلول شبكات متميزة مصممة للاستقرار والأداء",
    "home.cta.title": "هل أنت مستعد لتحويل البنية التحتية الخاصة بك؟",
    "home.cta.subtitle": "انضم إلى آلاف المحترفين الذين يستخدمون ستور هاب لتشغيل شبكاتهم.",
    "home.cta.browse": "تصفح المنتجات",
    "home.cta.createAccount": "إنشاء حساب",

    // Dashboard
    "dashboard.myOrders": "طلباتي",
    "dashboard.noOrders": "لا توجد طلبات بعد",
    "dashboard.startShopping": "ابدأ التسوق لرؤية طلباتك هنا.",
    "dashboard.order": "الطلب",
    "dashboard.items": "عناصر",
    "dashboard.status": "الحالة",
    "dashboard.paymentPending": "الدفع معلق",
    "dashboard.estimatedDelivery": "التسليم المتوقع",
    "dashboard.processingOrders": "الطلبات قيد المعالجة",

    // Profile
    "profile.title": "إعدادات الملف الشخصي",
    "profile.subtitle": "إدارة إعدادات حسابك وتفضيلاتك",
    "profile.tabs.profile": "الملف الشخصي",
    "profile.tabs.security": "الأمان",
    "profile.tabs.notifications": "الإشعارات",
    "profile.tabs.preferences": "التفضيلات",
    "profile.phone": "رقم الهاتف",
    "profile.address": "العنوان",
    "profile.currentPassword": "كلمة المرور الحالية",
    "profile.newPassword": "كلمة المرور الجديدة",
    "profile.confirmPassword": "تأكيد كلمة المرور",
    "profile.changePassword": "تغيير كلمة المرور",
    "profile.notifications.email": "إشعارات البريد الإلكتروني",
    "profile.notifications.email.desc": "تلقي الإشعارات عبر البريد الإلكتروني",
    "profile.notifications.push": "الإشعارات الفورية",
    "profile.notifications.push.desc": "تلقي الإشعارات الفورية",
    "profile.notifications.sms": "إشعارات الرسائل النصية",
    "profile.notifications.sms.desc": "تلقي الإشعارات عبر الرسائل النصية",
    "profile.language": "اللغة",
    "profile.language.desc": "اختر لغتك المفضلة",
    "profile.theme": "المظهر",
    "profile.theme.desc": "اختر المظهر المفضل لديك",
    "profile.theme.light": "المظهر الفاتح",
    "profile.theme.dark": "المظهر الداكن",

    // Notifications
    "notifications.title": "الإشعارات",
    "notifications.unread": "إشعارات غير مقروءة",
    "notifications.allRead": "جميع الإشعارات مقروءة",
    "notifications.markAllRead": "تحديد الكل كمقروء",
    "notifications.clearAll": "مسح الكل",
    "notifications.filter.all": "الكل",
    "notifications.filter.unread": "غير مقروء",
    "notifications.filter.read": "مقروء",
    "notifications.empty.title": "لا توجد إشعارات",
    "notifications.empty.subtitle": "أنت محدث بكل شيء!",
    "notifications.markRead": "تحديد كمقروء",
    "notifications.delete": "حذف",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحباً بعودتك",
    "dashboard.stats.orders": "إجمالي الطلبات",
    "dashboard.stats.points": "رصيد النقاط",
    "dashboard.stats.spent": "إجمالي المبلغ المنفق",
    "dashboard.recentOrders": "الطلبات الأخيرة",
    "dashboard.pointsHistory": "تاريخ النقاط",

    // Admin
    "admin.title": "لوحة تحكم المدير",
    "admin.users": "المستخدمين",
    "admin.products": "المنتجات",
    "admin.orders": "الطلبات",
    "admin.analytics": "التحليلات",
    "admin.notifications": "الإشعارات",

    // Auth
    "auth.login.title": "تسجيل الدخول",
    "auth.login.subtitle": "مرحباً بعودتك إلى ستور هاب",
    "auth.register.title": "إنشاء حساب",
    "auth.register.subtitle": "انضم إلى ستور هاب اليوم",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.phone": "رقم الهاتف",
    "auth.name": "الاسم الكامل",
    "auth.role": "نوع الحساب",
    "auth.role.individual": "فردي",
    "auth.role.company_admin": "مدير شركة",
    "auth.role.company_staff": "موظف شركة",
    "auth.role.affiliate": "مسوق",
    "auth.companyName": "اسم الشركة",
    "auth.register.companyName": "اسم الشركة",
    "auth.register.companyName.placeholder": "ادخل اسم الشركة",
    "auth.register.companyEmail": "البريد الإلكتروني للشركة",
    "auth.register.companyEmail.placeholder": "ادخل بريد الشركة",
    "auth.register.companyEmail.hint": " يجب استخدام البريد الرسمي للشركة",
    "auth.register.commercialRegister": "صورة السجل التجاري",
    "auth.register.taxCard": "صورة البطاقة الضريبية",
    "auth.register.affiliateCompany": "اسم الشركة",
    "auth.register.affiliateCompany.placeholder": "ادخل اسم شركتك",
    "auth.register.affiliateJobTitle": "المسمى الوظيفي",
    "auth.register.affiliateJobTitle.placeholder": "ادخل المسمى الوظيفي",
    "auth.register.affiliateReason": "لماذا تريد العمل معنا؟",
    "auth.register.affiliateReason.placeholder":
      "اكتب سبب رغبتك في الانضمام...",
    "auth.role.salesCommission": "العمل بالعمولة",
    "auth.register.name.placeholder": "ادخل اسمك الكامل",
    "auth.register.email.placeholder": "ادخل بريدك الإلكتروني",
    "auth.register.password.placeholder": "انشئ كلمة مرور",
    "auth.register.haveAccount": "هل لديك حساب بالفعل؟",
    "auth.register.phoneRequired": "رقم الهاتف مطلوب",
    "auth.register.phoneInvalid": "رقم الهاتف غير صالح",
    "auth.register.phone.placeholder": "ادخل رقم هاتفك",

    "auth.forgotPassword.title": "هل نسيت كلمة المرور؟",
    "auth.forgotPassword.subtitle":
      "أدخل بريدك الإلكتروني  وسنرسل لك رمزًا لإعادة تعيين كلمة المرور.",
    "auth.forgotPassword.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "auth.forgotPassword.sendCode": "إرسال رمز إعادة التعيين",
    "auth.forgotPassword.login": "العودة لتسجيل الدخول",
    "auth.forgotPassword.checkEmail": "تحقق من بريدك الإلكتروني",
    "auth.forgotPassword.sentTo": "لقد أرسلنا رمز إعادة تعيين كلمة المرور إلى",
    "auth.forgotPassword.enterCode": "أدخل رمز إعادة التعيين",
    "auth.forgotPassword.codeSent": "تم إرسال الرمز ",

    "auth.resetPassword.title": "إعادة تعيين كلمة المرور",
    "auth.resetPassword.subtitle": "أدخل رمز إعادة التعيين",
    "auth.resetPassword.newPassword": "كلمة المرور الجديدة",
    "auth.resetPassword.newPasswordPlaceholder": "أدخل كلمة المرور الجديدة",
    "auth.resetPassword.confirmPassword": "تأكيد كلمة المرور الجديدة",
    "auth.resetPassword.confirmPasswordPlaceholder": "أكد كلمة المرور الجديدة",
    "auth.resetPassword.resetButton": "إعادة تعيين كلمة المرور",
    "auth.resetPassword.resetting": "جاري إعادة تعيين كلمة المرور...",
    "auth.resetPassword.resendCode": "إعادة إرسال الرمز",
    "auth.resetPassword.didntReceive": "لم تستلم الرمز؟",
    "auth.resetPassword.backToLogin": "العودة لتسجيل الدخول",

    // Login
    "auth.login.email": "البريد الإلكتروني",
    "auth.login.password": "كلمة المرور",
    "auth.login.emailPlaceholder": "ادخل بريدك الإلكتروني",
    "auth.login.passwordPlaceholder": "ادخل كلمة المرور",
    "auth.login.forgotPassword": "هل نسيت كلمة المرور؟",
    "auth.login.dontHaveAccount": "ليس لديك حساب؟",
    "auth.login.noAccount": "ليس لديك حساب؟",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const initialLang =
    (localStorage.getItem("storehub_language") as "en" | "ar") || "en";

  const [language, setLanguage] = useState<"en" | "ar">(initialLang);

  useEffect(() => {
    const savedLang = localStorage.getItem("storehub_language") as "en" | "ar";
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
    localStorage.setItem("storehub_language", language);
  }, [language]);

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
